'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = __dirname;
const read = file => fs.readFileSync(path.join(root, file), 'utf8');

const motion = require('./app/motion.js');
assert.strictEqual(motion.stripLuaComments('-- movement settings\nlocal speed = 100 -- player speed'), '\nlocal speed = 100 ');
assert.strictEqual(motion.stripLuaComments("print('-- stays') -- removed"), "print('-- stays') ");
assert.strictEqual(motion.stripLuaComments('print("-- stays") -- removed'), 'print("-- stays") ');
assert.strictEqual(motion.stripLuaComments('local text = [[-- long string]] -- removed'), 'local text = [[-- long string]] ');
assert.strictEqual(motion.stripLuaComments('local text = [=[-- long string]=]\n--[=[ hidden\ncomment ]=]\nprint(text)'), 'local text = [=[-- long string]=]\n\n\nprint(text)');
assert.strictEqual(motion.stripLuaComments('a() --[==[ hidden ]==]\nb()'), 'a() \nb()');
assert.strictEqual(motion.selectSourceSnippet('   \n\nlocal function add(a, b)\n    return a + b\nend\nprint(add(1, 2))'), 'local function add(a, b)\n    return a + b\nend\nprint(add(1, 2))');
assert.strictEqual(motion.selectSourceSnippet(''), '');
assert.strictEqual(motion.selectSourceSnippet('\n  print(1)'), '  print(1)');
assert.strictEqual(motion.selectSourceSnippet('-- heading\nlocal speed = 100 -- inline\n\n-- next\nprint("-- string", speed)'), 'local speed = 100 \nprint("-- string", speed)');
assert.strictEqual(motion.selectSourceSnippet('-- comments only\n-- nothing visible'), '');
assert(motion.selectSourceSnippet(`local value = "${'x'.repeat(120)}"`).split('\n')[0].length <= 92);
assert(motion.selectSourceSnippet('local a = 1\nlocal b = 2\nlocal c = 3\nlocal d = 4\nlocal e = 5\nlocal f = 6\nlocal g = 7').split('\n').length <= 6);

const preview = 'local function calculateDamage(player)\n    local damage = player.Health * 2\n    print("damage", damage)\n    return damage\nend';
const tokens = motion.tokenizePreview(preview);
assert(tokens.some(token => token.type === 'keyword' && token.value === 'local'));
assert(tokens.some(token => token.type === 'property' && token.value === 'Health' && token.eligible));
assert(tokens.some(token => token.type === 'string' && token.value === '"damage"'));
assert(tokens.some(token => token.type === 'operator' && token.value === '*'));
assert(tokens.some(token => token.type === 'punctuation' && token.value === '('));
assert(tokens.filter(token => token.value === 'print').every(token => !token.eligible));
assert(tokens.filter(token => token.type === 'keyword').every(token => !token.eligible));
const methodTokens = motion.tokenizePreview('object:Run(config.value)');
assert(methodTokens.some(token => token.type === 'property' && token.value === 'Run'));
assert(methodTokens.some(token => token.type === 'property' && token.value === 'value'));

const plan = motion.createIdentifierPlan(tokens, () => 0, 10);
assert.deepStrictEqual(plan.steps.map(step => step.identifier), ['calculateDamage', 'player', 'damage', 'Health']);
assert.strictEqual(new Set(plan.steps.map(step => step.replacement)).size, plan.steps.length);
const firstStage = motion.renderTokenText(tokens, plan, 1);
const secondStage = motion.renderTokenText(tokens, plan, 2);
assert(!firstStage.includes('calculateDamage') && firstStage.includes('player.Health'));
assert(!secondStage.includes('calculateDamage') && !secondStage.includes('player.Health'));
assert(secondStage.includes('local damage') && secondStage.includes('return damage'));
const finalStage = motion.renderTokenText(tokens, plan, plan.steps.length);
assert(!finalStage.includes('calculateDamage') && !finalStage.includes('player.Health'));
assert(!finalStage.includes('local damage') && !finalStage.includes('return damage'));
assert(finalStage.includes('local function') && finalStage.includes('print("damage"'));
assert.strictEqual(motion.createTokenGlitchFrame('calculateDamage', 0, () => 1), 'calculateDamage');
const sequentialPlan = motion.createSequentialTokenPlan(motion.tokenizePreview('local value = source + value'), () => 0, 10);
assert.deepStrictEqual(sequentialPlan.steps.map(step => step.identifier), ['value', 'source', 'value']);
assert(sequentialPlan.steps[0].tokenIndex < sequentialPlan.steps[1].tokenIndex && sequentialPlan.steps[1].tokenIndex < sequentialPlan.steps[2].tokenIndex);
assert.strictEqual(sequentialPlan.steps[0].replacement, sequentialPlan.steps[2].replacement, 'repeated identifiers should keep a stable replacement');
const protectedPlan = motion.createProtectedPreviewPlan(motion.tokenizePreview('local value = "hello" .. 42'), () => 0, 20);
assert.deepStrictEqual(protectedPlan.steps.map(step => step.type), ['keyword', 'identifier', 'operator', 'string', 'operator', 'number']);
assert(protectedPlan.steps.find(step => step.type === 'identifier').replacement.startsWith('_0x'));
assert(protectedPlan.steps.find(step => step.type === 'string').replacement.startsWith('_K['));
assert(protectedPlan.steps.find(step => step.type === 'number').replacement.startsWith('_N['));
assert.strictEqual(motion.createCharacterMorphFrame('value', '_0xABC', 0, () => 0), '#alue');
assert(motion.createCharacterMorphFrame('value', '_0xABC', 3, () => 0).startsWith('_0x'));

const routerSource = read('app/router.js');
const routerContext = { window: {}, module: { exports: {} }, URL, URLSearchParams };
vm.runInNewContext(routerSource, routerContext, { filename: 'router.js' });
const Router = routerContext.window.SukaRedRouter;
const router = new Router([{ path: '/', title: 'Landing' }, { path: '/workspace', title: 'Workspace' }, { path: '/changelog', title: 'Changelog' }, { path: '*', title: '404' }]);
assert.strictEqual(router.normalize('/'), '/');
assert.strictEqual(router.match('/workspace').route.title, 'Workspace');
assert.strictEqual(router.match('/changelog').route.title, 'Changelog');
assert.strictEqual(router.match('/missing').route.title, '404');
routerContext.location = { pathname: '/', search: '', hash: '#/workspace?auth=success' };
assert.strictEqual(router.locationState().pathname, '/workspace');
assert.strictEqual(new URLSearchParams(router.locationState().search).get('auth'), 'success');

const main = read('app/main.js');
const dashboard = read('app/dashboard.js');
const transition = read('app/transition.js');
const settings = read('app/history-store.js');
const html = read('index.html');
const changelog = read('app/changelog-data.js');
const css = read('style.css');
assert(main.includes("route('/', 'Welcome'"));
assert(main.includes("route('/workspace', 'Workspace'"));
assert(main.includes("route('/changelog', 'Changelog'"));
assert(dashboard.includes("JSON.stringify({ code, profile: currentSettings.profile })"), 'request payload changed');
assert(dashboard.includes('window.SukaRedTransition.begin(code)'), 'transition is not connected to the production request');
for (const stage of ['queued', 'analyzing', 'preparing', 'virtualizing', 'protecting', 'integrity', 'finalizing']) {
    assert(transition.includes(`['${stage}'`) || transition.includes(`, ['${stage}'`), `missing live build stage: ${stage}`);
}
assert(transition.includes('pipeline-scan'), 'pipeline scan visualization is missing');
assert(transition.includes('createProtectedPreviewPlan(tokens, Math.random, 8)'), 'bounded protected block preview is not connected');
assert(transition.includes('sourceLines.map'), 'source-region block animation is missing');
assert(transition.includes('createCharacterMorphFrame('), 'progressive line morphing is missing');
assert(transition.includes('const animationDone = morph()'), 'completed builds do not wait for the visible transformation');
assert(transition.includes('const finalLineReady = new Promise'), 'animation is not synchronized with backend completion');
assert(transition.includes('accelerated = true') && transition.includes('releaseFinalLine()'), 'fast-build acceleration is missing');
assert(transition.includes('const pacedDelay = async'), 'active animation waits cannot react to a fast build');
assert(!transition.includes('block.text.textContent = block.original;'), 'protected lines must not revert to plaintext');
assert(transition.includes('const setStage'), 'live stage API is missing');
assert(transition.includes("current.textContent = 'COMPLETE'"), 'terminal completion state is missing');
assert(transition.includes('overlay.remove(); active = null'), 'preview state is not cleared');
assert(!transition.includes('innerHTML'), 'unsafe transition rendering returned');
assert(!settings.includes('sourceCode') && !settings.includes('inputSource'), 'settings must not persist source');
assert(settings.includes("window.LuavexAPI.request('/builds/history')"), 'history is not account-backed');
assert(!settings.includes('indexedDB'), 'local build history storage returned');
assert(main.includes('hashQuery || location.search'), 'OAuth callback result handling is missing');
for (const sensitiveQuery of ["get('source')", "get('code')", "get('output')", "get('seed')"]) {
    assert(!main.includes(sensitiveQuery), `sensitive URL state returned: ${sensitiveQuery}`);
}
assert(html.includes('href="/#/workspace"') && html.includes('href="/#/changelog"'));
assert(routerSource.includes("hash.startsWith('#/')"), 'static-host hash routing is missing');
assert(html.includes('id="accountSlot"') && html.includes('href="/#/history"'), 'account navigation is missing');
assert(html.includes('Luavex 1.2') && main.includes('Luavex 1.2'), 'public version is inconsistent');
assert(html.includes('/assets/luavex-brand.png'), 'Luavex logo asset is not connected');
assert(read('app/landing.js').includes("start.textContent = 'START'"), 'landing action label must be START');
assert(changelog.indexOf('Version 1.2') < changelog.indexOf('Version 1.1'), 'current release must appear first');
assert(changelog.includes("status: 'Current Beta'") && changelog.includes("status: 'Previous Beta'"));
for (const internalTerm of ['opcode', 'bytecode', 'interpreter', 'upvalue', 'virtualization']) assert(!changelog.toLowerCase().includes(internalTerm), `changelog exposes ${internalTerm}`);
assert(!html.includes('ambient-particles'));
const ui = read('app/ui.js');
assert(ui.includes("id: 'hell'") && ui.includes("status: 'Experimental'") && ui.includes('enabled: true'), 'public Hell Experimental profile is missing');
assert(ui.includes('Practical daily protection with strong compatibility.'), 'Good positioning copy is missing');
assert(ui.includes('Stronger protection for important production scripts.'), 'Pro positioning copy is missing');
assert(ui.includes('Maximum experimental protection for high-value scripts.'), 'Hell positioning copy is missing');
for (const profile of ['blatant', 'fatality']) assert(ui.includes(`id: '${profile}'`) && ui.includes('enabled: false'), `${profile} locked profile presentation is missing`);
assert(dashboard.includes("currentSettings.profile === 'hell'"), 'Hell confirmation gate is missing');
assert(dashboard.includes('Hell is an experimental maximum protection profile.'), 'Hell warning copy is missing');
assert(dashboard.indexOf("currentSettings.profile === 'hell'") < dashboard.indexOf('window.SukaRedTransition.begin(code)'), 'Hell confirmation must run before the build transition');
assert(dashboard.includes("credentials: 'include'"), 'authenticated build credentials are missing');
assert(dashboard.includes('/builds/status/'), 'live build status polling is missing');
assert(dashboard.includes('Connect Discord to build'), 'authentication gate copy is missing');
assert(dashboard.includes('The build server could not be reached.') && dashboard.includes('Attempted API URL:'), 'sanitized network error UX is missing');
assert(css.includes('@media (max-width: 720px)') && css.includes('.build-controls'), 'mobile workspace controls are missing');
assert(css.includes('@media (prefers-reduced-motion: reduce)'), 'reduced-motion support is missing');
assert(css.includes('.pipeline-scan') && css.includes('.account-popover'), 'production UX styling is incomplete');

console.log('Luavex frontend tests passed');
