'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
let listener, removed = false, focused = false, scrolled = false, prevented = false;
const target = { setAttribute(name, value) { assert.equal(name, 'tabindex'); assert.equal(value, '-1'); }, focus() { focused = true; }, scrollIntoView() { scrolled = true; } };
const page = { innerHTML: '', querySelector(selector) { assert.equal(selector, '#webPreview'); return target; }, addEventListener(name, fn) { assert.equal(name, 'click'); listener = fn; }, removeEventListener(name, fn) { assert.equal(fn, listener); removed = true; } };
const context = { window: {}, document: { createElement() { return page; } } };
vm.runInNewContext(fs.readFileSync('app/release.js', 'utf8'), { window: context.window, document: { querySelectorAll() { return []; } } });
vm.runInNewContext(fs.readFileSync('app/landing.js', 'utf8'), context);
let mounted;
const cleanup = context.window.SukaRedLanding.mount({ replaceChildren(node) { mounted = node; } });
assert.equal(mounted, page);
assert.equal((page.innerHTML.match(/<h1 /g) || []).length, 1);
assert(page.innerHTML.includes('Luavex 2.1 · Current release'));
assert(!/Upcoming|Not released|in preparation|1.9 available/.test(page.innerHTML));
assert(page.innerHTML.includes('Previous release'));
assert(page.innerHTML.includes('Luavex 2.0'));
assert(page.innerHTML.includes('Values can still be observed at runtime'));
for (const internal of ['checkpoint', 'header dialect', 'token fragment', 'decoder formula', 'attacker fixture']) assert(!page.innerHTML.includes(internal));
listener({ target: { closest() { return { getAttribute() { return '#webPreview'; } }; } }, button: 0, preventDefault() { prevented = true; } });
assert(focused && scrolled && prevented, 'section navigation must focus and scroll without route change');
cleanup(); assert(removed, 'route cleanup must detach section navigation');
vm.runInNewContext(fs.readFileSync('app/changelog-data.js', 'utf8'), context);
const releases = context.window.SukaRedChangelog;
assert.equal(releases[0].status, 'Current');
assert.equal(releases.filter(r => r.status === 'Current').length, 1);
assert.equal(releases.find(r => r.status === 'Current').version, 'Luavex 2.1 — Runtime Execution Diversity');
assert.equal(releases.find(r => r.version === 'Version 1.9').status, 'Previous');
assert.equal(releases.find(r => r.version === 'Luavex 2.0 — VM Architecture Redesign').status, 'Previous');
const publicRelease = JSON.stringify(releases[0]);
for (const internal of ['checkpoint', 'scalar', 'nonce', 'transcript', 'RSA', 'decoder', 'cache', 'handoff', 'header']) assert(!publicRelease.includes(internal));
assert.equal(releases.find(r => r.version === 'Version 1.8').status, 'Previous');
assert.equal(releases.find(r => r.version === 'Version 1.7 Beta').status, 'Previous');
const html = fs.readFileSync('index.html', 'utf8');
assert(html.includes('"softwareVersion":"' + context.window.LuavexRelease.version + '"'));
assert.equal(releases[0].version.split(' — ')[0], context.window.LuavexRelease.name);
for (const file of ['app/main.js', 'app/dashboard.js', 'app/views.js']) {
    const source = fs.readFileSync(file, 'utf8');
    assert(source.includes('window.LuavexRelease.'), file + ' must use the frontend release source');
    assert(!/Luavex 1\.9|1\.9 is the current/.test(source));
}
console.log('Public preview content, release status, section navigation and cleanup: PASS');
